import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import Layout from "../layout/Layout";
import TopCharts from "../components/homepage/topCharts/TopCharts";
import SquareLoader from "../components/loader/SquareLoader";
import TopArtists from "../components/homepage/topArtists/TopArtists";
import HomeCarousel from "../components/homepage/carousel/HomeCarousel";
import { HiChevronRight } from "react-icons/hi";

export default function Home() {
  const APIurl = process.env.NEXT_PUBLIC_LASTFM_API_URL;
  const [topThreeChart, setTopThreeChart] = useState();
  const [topFiveArtists, setTopFiveArtists] = useState();
  const [isLoading, setIsLoading] = useState(false);
  const requestMethod = {
    charts: "chart.gettoptracks",
    artists: "chart.gettopartists",
  };

  useEffect(() => {
    fetchTopChartsData();
    fetchTopArtistsData();
  }, []);

  const fetchTopChartsData = async () => {
    try {
      setIsLoading(true);
      const response = await axios.get(
        `${APIurl}/?format=json&method=${requestMethod.charts}&api_key=${process.env.NEXT_PUBLIC_LASTFM_API_KEY}`
      );
      const topThree = response.data.tracks.track.slice(0, 3);
      setTopThreeChart(topThree);
      setIsLoading(false);
    } catch (error) {
      console.error(error);
    }
  };

  const fetchTopArtistsData = async () => {
    try {
      setIsLoading(true);
      const response = await axios.get(
        `${APIurl}/?format=json&method=${requestMethod.artists}&api_key=${process.env.LASTFM_API_KEY}`
      );
      const topFive = response.data.artists.artist.slice(0, 5);
      setTopFiveArtists(topFive);
      setIsLoading(false);
      console.log(topFive);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Layout withMenu={true}>
      <div className="p-4">
        <Head>
          <title>Music App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomeCarousel />
        <div className="top-charts mt-5">
          <div className="flex justify-between">
            <h4 className="text-md font-medium text-white">Top Charts</h4>
            <Link href="/detail/chart">
              <a>
                <span className="flex items-center">
                  <p className="text-white text-[14px]">See all</p>
                  <HiChevronRight className="w-6 h-6 text-white" />
                </span>
              </a>
            </Link>
          </div>
          {isLoading ? (
            <SquareLoader count="3" />
          ) : (
            <TopCharts chartData={topThreeChart} />
          )}
        </div>
        <div className="top-artists mt-5">
          <div className="flex justify-between">
            <h4 className="text-md font-medium text-white">Top Artists</h4>
            <Link href="/detail/artist">
              <a>
                <span className="flex items-center">
                  <p className="text-white text-[14px]">See all</p>
                  <HiChevronRight className="w-6 h-6 text-white" />
                </span>
              </a>
            </Link>
          </div>

          {isLoading ? (
            <SquareLoader count="3" />
          ) : (
            <TopArtists artistsData={topFiveArtists} />
          )}
        </div>
      </div>
    </Layout>
  );
}
