import React from "react";
import Head from "next/head";
import Menu from "./menu/Menu";

function Layout(props) {
  return (
    <div className="bg-black h-[screen] w-full ">
      <Head>
        <title>Music App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-y-auto first-letter:m-0 p-0 pb-10 bg-black border-r border-l border-[#1E1E1E] mx-auto h-[100%] md:w-[40%] lg:w-[30%] lg:max-w-[40%] sm:w-[100%] sm:max-w-[100%]">
        <div className="h-screen max-h-[100%]">{props.children}</div>
        {props.withMenu && <Menu />}
      </main>
    </div>
  );
}

export default Layout;
